-- Run all schema files in order

\i schema/001_create_user_roles.sql
\i schema/002_create_workspaces.sql
\i schema/003_create_users.sql
\i schema/004_create_teams.sql
\i schema/005_create_projects.sql
\i schema/006_create_milestones.sql
\i schema/007_create_issues.sql
\i schema/008_create_comments.sql
\i schema/009_create_issue_labels.sql
\i schema/010_create_reactions.sql
\i schema/011_create_issue_label_relations.sql
\i schema/012_create_issue_subscriptions.sql
\i schema/013_create_comment_subscriptions.sql
\i schema/014_create_issue_favorites.sql
\i schema/015_create_comment_reactions.sql
\i schema/016_create_indexes.sql
\i schema/017_create_links.sql
\i schema/018_create_issue_related_issues.sql
\i schema/019_create_workspace_memberships.sql
\i schema/020_create_team_memberships.sql
\i schema/021_enable_rls.sql
\i schema/022_create_milestone_stats_view.sql
\i schema/023_create_user_role_assignment_events.sql
\i seeds/001_initial_reactions.sql
\i seeds/002_seed_workspaces.sql
\i seeds/003_seed_user_roles.sql
\i seeds/004_seed_users.sql
\i seeds/005_seed_workspace_memberships.sql
\i seeds/006_seed_teams.sql
\i seeds/007_seed_team_memberships.sql
\i seeds/008_seed_projects.sql
\i seeds/009_seed_milestones.sql
\i seeds/010_seed_issue_labels.sql
\i seeds/011_seed_issues.sql
\i seeds/012_seed_comments.sql
\i seeds/013_seed_user_role_assignment_events.sql
\i seeds/014_seed_comment_reactions.sql
\i seeds/015_seed_issue_label_relations.sql
\i seeds/016_seed_issue_subscriptions.sql
\i seeds/017_seed_issue_favorites.sql
\i seeds/018_seed_comment_subscriptions.sql
\i seeds/019_seed_issue_related_issues.sql
\i seeds/020_seed_links.sql